name: Publish Docker

on:
  push:
    branches: [ 'master' ]

jobs:

  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHB_TOKEN }}
      - name: Set Image Name
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Push Image to Github Container Registry
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
